name: Build devcontainer image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - script/requirements.txt
      - .github/workflows/devcontainer-build.yaml
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**
      - script/requirements.txt
      - .github/workflows/devcontainer-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        if: github.event_name != 'pull_request'
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Build and Push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer:addons
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
