name: Build devcontainer image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        if: github.event_name != 'pull_request'
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer:addons
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
